### ISSUE TITLE
Can this host 2 or more instances of an existing vst3 in a new vst3?

### ISSUE THREAD

**Issue by probonopd** [blitcrush/EasyVst#4]
Hi, I'd like to [make a vst3 that hosts 2 or more instances of an existing vst3](https://github.com/probonopd/MultiDexed), and plays them simultaneously with a few parameters different between the instances of the vst3.

Additionally, what if I'd like to stereo shift (pan) each of the hosted instances?

Would making such a vst be possible with EasyVst, and how hard would it be? Where would one begin?

Thank you very much.

**Comment by iffyloop** [comment]
EasyVst won't handle packaging the VST plugin for you (for that you should use a framework like iPlug2 or JUCE), but it will help you host the external VST instances inside your plugin. What you'll want to do is create an instance of the `EasyVst` class for each external VST you want to have hosted in your plugin and use that class to apply plugin processing. After all individual plugins have processed, you can pan and mix them yourself. Hope this helps! Let me know if this works for you or if you need anything else.

**Comment by probonopd** [comment]
Thanks @iffyloop. You don't happen to have some example code to share, do you?

I had tried to make [this](https://github.com/probonopd/MultiDexed) with JUCE but I can't get sound out of it.

**Comment by syntaro** [comment]
Hello probonopd. and iffyloop.

I made Customed EasyVSTCustom.cpp

[CustomEasyVst.cpp](https://osdn.net/projects/midimixer/scm/git/master/blobs/master/mixrecipe/src/2023-03-24-beta/MXLIB02/CustomEasyVst.cpp)

And [MXVSTOperator.cpp](https://osdn.net/projects/midimixer/scm/git/master/blobs/master/mixrecipe/src/2023-03-24-beta/MXLIB02/MXVSTOperator.cpp)

manages resources. this is important.
only 1 thread can ownership of VST.

#Sorry this is not GitHub website.

Binary  Released(https://osdn.net/projects/midimixer/releases) But mine Is Processing Congstruction.

And, excuse me, Iffyloop, I have a question.

Do you mind If I make customed EasyVST on my OSS. GPL3? or another license.

Thank you.
Steinberg Forum said, OSS with VST sdk all GPL3?

**Comment by syntaro** [comment]
oh. mistake

https://ja.osdn.net/projects/midimixer/scm/git/master/blobs/master/mixrecipe/src/2023-03-21-beta/MXLIB02/CustomEasyVst.cpp

is it.

**Comment by syntaro** [comment]
But I m thinking.
Base EasyVST is very kind for us.
Customize is easy. and little excited. I felt.
Best reference code.

Educational use, Its perfectly.

Maybe it is joy. Thank you.
And, I wish my Customize code can help probonopd's wish multi vst hosting with custom EasyVST

**Comment by iffyloop** [comment]
@probonopd I don't have any examples other than [this](https://github.com/iffyloop/EasyVst/blob/main/examples/SimpleMidiExample.cpp), sorry. The code syntaro shared looks promising but appears to contain portions which are specific to the Win32 API (not cross-platform).

@syntaro Thanks for the kind words! EasyVst is public-domain software, so you're free to do whatever you want with it!
However, you are correct that the Steinberg VST3 SDK is dual-licensed under GPL or proprietary terms. If you choose to link your product with the VST3 SDK, then the GPL license will carry over to your product unless you agree to Steinberg's other terms (which are more friendly to commercial usage). IIRC the Steinberg license is free but you just have to get in contact with them and send them a document. More details: https://www.steinberg.net/developers/
Disclaimer: I am not a lawyer and this is not legal advice.

**Comment by syntaro** [comment]
@iffyloop Thank you. I agree GPL3, Ill try it.
and
@probonopd good luck, you too.
